/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoadso;
import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author APRENDIZ
 */
public class formularioclientes extends javax.swing.JFrame {

    /**
     * Creates new form formularioclientes
     */
    public formularioclientes() {
        initComponents();
    }
    void mostrardatos(String valor){
    
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("cedula");
    modelo.addColumn("nombre");
    modelo.addColumn("direccion");
    modelo.addColumn("telefono");
    tablapersona.setModel(modelo);
    String sql="";
    if (valor.equals("")){
        JOptionPane.showMessageDialog(null ,  "!No se digito nada¡, se mostraran todos los datos");
        sql="SELECT * FROM clientes";
    }else{
        sql="SELECT * FROM clientes WHERE cedula= '"+valor+"'";
    }
    String []datos =new String[4];
    try {
        Statement st= cn.createStatement();
        ResultSet rs =st.executeQuery(sql);
        while (rs.next()){
        datos[0]=rs.getString(1);
        datos[1]=rs.getString(2);
        datos[2]=rs.getString(3);
        datos[3]=rs.getString(4);
        
        modelo.addRow(datos);
        }
        tablapersona.setModel(modelo);
    }catch(SQLException ex){
        
    }}
    void eliminardatos(String valor){
    
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("cedula");
    modelo.addColumn("nombre");
    modelo.addColumn("direccion");
    modelo.addColumn("telefono");
    tablapersona.setModel(modelo);
    
    String sql="";
    sql="DELETE FROM clientes WHERE cedula=cedula";
    String []datos =new String[4];
    try {
        Statement st= cn.createStatement();
        ResultSet rs =st.executeQuery(sql);
        while (rs.next()){
        datos[0]=rs.getString(1);
        modelo.addRow(datos);
        }
        tablapersona.setModel(modelo);
    }catch(SQLException ex){
        
    }}
     void btnmodificarActionPerformed(String valor) {                                            
    int filaSeleccionada = tablapersona.getSelectedRow();

    if (filaSeleccionada >= 0) {
        String cedulaCliente = (String) tablapersona.getValueAt(filaSeleccionada, 0); // Suponiendo que la cédula está en la primera columna (índice 0)

        // Obtener los nuevos valores desde los campos de texto
        String nuevaCedula = cedula.getText();
        String nuevoNombre = nombre.getText();
        String nuevaDireccion = direccion.getText();
        String nuevoTelefono = telefono.getText();

        // Actualizar registro en la base de datos
        try {
            PreparedStatement pst = cn.prepareStatement("UPDATE CLIENTES SET cedula = ?, nombre = ?, direccion = ?, telefono = ? WHERE cedula = ?");
            pst.setString(1, nuevaCedula);
            pst.setString(2, nuevoNombre);
            pst.setString(3, nuevaDireccion);
            pst.setString(4, nuevoTelefono);
            pst.setString(5, cedulaCliente);
            pst.execute();
            JOptionPane.showMessageDialog(null, "REGISTRO MODIFICADO");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al modificar el registro: " + ex.getMessage());
        }

        // Actualizar la tabla en la interfaz
        mostrardatos("");
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona una fila para modificar");
    }}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablapersona = new javax.swing.JTable();
        btnlistar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cajabuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 450, -1));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 450, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 450, -1));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 450, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel2.setText("CEDULA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel3.setText("DIRECCION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel4.setText("TELEFONO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel5.setText("REGISTRO DE CLIENTES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        guardar.setBackground(new java.awt.Color(153, 0, 153));
        guardar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("REGISTRAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 120, -1));

        tablapersona.setBackground(new java.awt.Color(204, 204, 255));
        tablapersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablapersona);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 670, 290));

        btnlistar.setBackground(new java.awt.Color(204, 204, 0));
        btnlistar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 120, -1));

        botoneliminar.setBackground(new java.awt.Color(204, 0, 0));
        botoneliminar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        botoneliminar.setText("ELIMINAR");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 120, -1));

        btnmodificar.setBackground(new java.awt.Color(0, 204, 255));
        btnmodificar.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 120, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 2, 12)); // NOI18N
        jLabel6.setText("BUSCAR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 70, 30));

        cajabuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajabuscarActionPerformed(evt);
            }
        });
        getContentPane().add(cajabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 560, -1));

        buscar.setText("🔍");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 50, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 600));

        jMenu1.setText("File");

        jMenuItem6.setText("jMenuItem6");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        try{
            PreparedStatement pst= cn.prepareStatement("insert into clientes values (?,?,?,?)");
            pst.setString(1,cedula.getText());
            pst.setString(2,nombre.getText());
            pst.setString(3,direccion.getText());
            pst.setString(4,telefono.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"DATOS ALMACENADOS");
       
               
                }catch(Exception e){
       
        }

    }//GEN-LAST:event_guardarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        
        mostrardatos("");
    }//GEN-LAST:event_btnlistarActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        // TODO add your handling code here:
        eliminardatos("");
        
        try{
            PreparedStatement pst= cn.prepareStatement("DELETE FROM clientes WHERE cedula = cedula (?)");
            pst.setString(1,cedula.getText());
            pst.setString(2,nombre.getText());
            pst.setString(3,direccion.getText());
            pst.setString(4,telefono.getText());
            
            JOptionPane.showMessageDialog(null,"Se eliminaro los datos correctamente");
       
               
            }catch(Exception i){
       
        }
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
         btnmodificarActionPerformed("");
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        //String sqlx="";
        //sqlx="SELECT * FROM clientes where cedula ='"+cajabuscar.getText()+"';";
        //String []datos = new String[4];
        //String cod="";
        mostrardatos(cajabuscar.getText());
    }//GEN-LAST:event_buscarActionPerformed

    private void cajabuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajabuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajabuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioclientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cajabuscar;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablapersona;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
conectar cc= new conectar();
       Connection cn = cc.conexion();
}

